force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Added_by_Admin__c.field-meta.xml
<CustomField>
    <fullName>Added_by_Admin__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this client was added by an Admin and will not be deleted by the nightly service.</description>
    <label>Added by Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <description>The unique identifier of this client.</description>
    <formula>Legal_Advisor__r.Account_Number__c &amp; Client_Number__c</formula>
    <label>Client Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ExistingClientFetcher.cls
public class ucl_ExistingClientFetcher {
    public static Map<String, Client__c> fetchClients(
        Map<String, Client__c> clientMap,
        Set<String> clientIdentifiers
    ) {
        for (Client__c existingClient : [
    		SELECT Id, Added_by_Admin__c, Client_Identifier__c
    		FROM Client__c
    		WHERE Client_Identifier__c IN :clientIdentifiers
		]) {
    		clientMap.put(existingClient.Client_Identifier__c, existingClient);
		}
        return clientMap;
    }
}