force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This object logs errors that happen during execution.</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Apex class that triggered this error.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <description>Dispalys detailed cause of the exception if Exception_Cause_Override__c is null</description>
    <label>Exception Cause</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The error message associated with the exception</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The type of the exception that triggered this error log.</description>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number where the exception occured</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The method of the class that caused an exception.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stores the stack trace from the exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ucl_LogException.cls
public class ucl_LogException extends Exception {
    public String StackTrace { get; set; }
    public String ClassName { get; set; }
    public String MethodName { get; set; }

    public void log(Exception ex) {
        extractExceptionData(ex);
        writeToObject(ex);
    }

    private void extractExceptionData(Exception ex) {
        StackTrace = ex.getStackTraceString().substringBefore('\n');
        ClassName = StackTrace.substringAfter('.').substringBefore('.');
        MethodName = StackTrace
            .substringBefore(':')
            .substringAfter(className)
            .substringAfter('.');
    }

    private void writeToObject(Exception ex) {
        Exception_Log__c log = new Exception_Log__c(
            Stack_Trace__c = ex.getStackTraceString(),
            Class_Name__c = ClassName,
            Method_Name__c = MethodName,
            Line_Number__c = ex.getLineNumber(),
            Exception_Type__c = ex.getTypeName(),
            Exception_Cause__c = String.valueOf(ex.getCause()),
            Exception_Message__c = ex.getMessage()
        );
        insert log;
    }
}