force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This object logs errors that happen during execution.</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The error message associated with the exception</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The type of the exception that triggered this error log.</description>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ExceptionLogTriggerTest.cls
@isTest
private class ucl_ExceptionLogTriggerTest {
    @isTest
    static void testSentMail() {
        Exception_Log__c log = new Exception_Log__c (
            Exception_Message__c = 'I am an error',
            Exception_Type__c = 'I am an error type'
        );
        Test.startTest();
        insert log;
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(1, emailInvocations, 'An email should be sent');
    }
}