force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This object logs errors that happen during execution.</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Apex class that triggered this error.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <description>Dispalys detailed cause of the exception if Exception_Cause_Override__c is null</description>
    <label>Exception Cause</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The error message associated with the exception</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The type of the exception that triggered this error log.</description>
    <label>Exception Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number where the exception occured</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The method of the class that caused an exception.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stores the stack trace from the exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ucl_LogExceptionTest.cls
@isTest
private class ucl_LogExceptionTest {

    @isTest
    static void testLogException() {
        ucl_LogException logger = new ucl_LogException();
        Exception errorResult;

        Test.startTest();
        try {
            Integer a = 1 / 0;
            System.assert(false, 'Exception did not occur');
        } catch (Exception ex) {
            errorResult = ex;
            logger.log(ex);
        }

        List<Exception_Log__c> logs = [SELECT Stack_Trace__c, Class_Name__c, Method_Name__c,
                                       Line_Number__c, Exception_Type__c,
                                       Exception_Cause__c, Exception_Message__c
                                       FROM Exception_Log__c LIMIT 1];
        Test.stopTest();
        System.assertNotEquals(null, errorResult, 'Expected an exception, received null instead');

        System.assertNotEquals(null, logs[0], 'Expected at least one result, received null');
        System.assertNotEquals(null, logs[0].Stack_Trace__c, 'Expected stack trace to not be null');
        System.assertNotEquals(null, logs[0].Class_Name__c, 'Expected class name to not be null');
        System.assertNotEquals(null, logs[0].Method_Name__c, 'Expected method name to not be null');
        System.assertNotEquals(null, logs[0].Line_Number__c, 'Expected line number to not be null');
        System.assertNotEquals(null, logs[0].Exception_Type__c, 'Expected exception type to not be null');
        System.assertNotEquals(null, logs[0].Exception_Message__c, 'Expected exception message to not be null');
    }
}