force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients.</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for this Legal Advisor</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Is this firm&apos;s account enabled or disabled?</description>
    <label>Account Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ExistingAdvisorFetcher.cls
public class ucl_ExistingAdvisorFetcher {
    public static Map<String, Legal_Advisor__c> fetchAdvisors(
        Map<String, Legal_Advisor__c> advisorMap,
        Set<String> accountNumbers
    ) {
        for (Legal_Advisor__c existingLegalAdvisor : [
            SELECT Id, Account_Status__c, Account_Number__c
            FROM Legal_Advisor__c
            WHERE Account_Number__c IN :accountNumbers
        ]) {
            advisorMap.put(existingLegalAdvisor.Account_Number__c, existingLegalAdvisor);
        }
        return advisorMap;
    }
}