force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients.</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>The name of this legal firm.</description>
    <label>Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for this Legal Advisor</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Is this firm&apos;s account enabled or disabled?</description>
    <label>Account Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_LegalAdvisorProcessor.cls
public class ucl_LegalAdvisorProcessor {
    public static List<Legal_Advisor__c> processLegalAdvisors(
        List<ucl_LegalAdvisor> importedLegalAdvisors,
        Map<String, Legal_Advisor__c> fetchedLegalAdvisorsMap
    ) {
        List<Legal_Advisor__c> legalAdvisorsToUpdate = new List<Legal_Advisor__c>();

        for (ucl_LegalAdvisor importedLegalAdvisor : importedLegalAdvisors) {
            Legal_Advisor__c fetchedLegalAdvisor = fetchedLegalAdvisorsMap.get(importedLegalAdvisor.AccountNumber);

            if (fetchedLegalAdvisor == null && importedLegalAdvisor.AccountStatus != 'Disabled') {
                Legal_Advisor__c newLegalAdvisor = createNewLegalAdvisor(importedLegalAdvisor);
                legalAdvisorsToUpdate.add(newLegalAdvisor);
            } else if (fetchedLegalAdvisor != null) {
                updateExistingLegalAdvisor(importedLegalAdvisor, fetchedLegalAdvisor, legalAdvisorsToUpdate);
            }
        }

        return legalAdvisorsToUpdate;
    }

    private static Legal_Advisor__c createNewLegalAdvisor(ucl_LegalAdvisor importedLegalAdvisor) {
        return new Legal_Advisor__c(
            Account_Number__c = importedLegalAdvisor.AccountNumber,
            Account_Name__c = importedLegalAdvisor.AccountName,
            Name = importedLegalAdvisor.AccountName,
            As_of_Date__c = dateFormatter(importedLegalAdvisor.AsOfDate),
            Account_Status__c = importedLegalAdvisor.AccountStatus
        );
    }

    private static void updateExistingLegalAdvisor(
        ucl_LegalAdvisor importedLegalAdvisor,
        Legal_Advisor__c fetchedLegalAdvisor,
        List<Legal_Advisor__c> legalAdvisorsToUpdate
    ) {
        if (importedLegalAdvisor.AccountStatus == 'Disabled') {
            fetchedLegalAdvisor.Account_Status__c = 'Disabled';
            legalAdvisorsToUpdate.add(fetchedLegalAdvisor);
        } else if (fetchedLegalAdvisor.Account_Status__c != 'Disabled') {
            fetchedLegalAdvisor.As_of_Date__c = dateFormatter(importedLegalAdvisor.AsOfDate);
            fetchedLegalAdvisor.Account_Name__c = importedLegalAdvisor.AccountName;
            fetchedLegalAdvisor.Name = importedLegalAdvisor.AccountName;
            legalAdvisorsToUpdate.add(fetchedLegalAdvisor);
        }
    }

    private static Date dateFormatter(String dateString) {
        List<String> dateComponents = dateString.split('/');
        Integer year = Integer.valueOf(dateComponents[2]);
        Integer month = Integer.valueOf(dateComponents[0]);
        Integer day = Integer.valueOf(dateComponents[1]);
        return Date.newInstance(year, month, day);
    }
}