force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients.</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>The name of this legal firm.</description>
    <label>Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique identifier for this Legal Advisor</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Is this firm&apos;s account enabled or disabled?</description>
    <label>Account Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ExistingAdvisorFetcherTest.cls
@isTest
public class ucl_ExistingAdvisorFetcherTest {
    @isTest
    static void testFetchAdvisors() {
        List<Legal_Advisor__c> legalAdvisors = new List<Legal_Advisor__c>();
        Set<String> accountNumbers = new Set<String>{'123asdf', '456asdf', '789asdf'};
        
        Integer counter = 1;
        for (String accNumber : accountNumbers) {
            Legal_Advisor__c advisor = new Legal_Advisor__c(
                Account_Number__c = accNumber,
                Account_Name__c = 'Test User #' + counter,
                Account_Status__c = 'Enabled',
                As_of_Date__c = Date.valueOf('2019-12-0' + counter)
            );
            counter++;
            legalAdvisors.add(advisor);
        }
        
        Test.startTest();
        insert legalAdvisors;
        Test.stopTest();
        
        Map<String, Legal_Advisor__c> advisorMap = new Map<String, Legal_Advisor__c>();
        advisorMap = ucl_ExistingAdvisorFetcher.fetchAdvisors(advisorMap);
        
        System.assertEquals(accountNumbers.size(), advisorMap.size(), 'Map size should match the input set size');
        
        for (Legal_Advisor__c advisor : legalAdvisors) {
            Legal_Advisor__c fetchedAdvisor = advisorMap.get(advisor.Account_Number__c);
            System.assertNotEquals(null, fetchedAdvisor, 'Fetched advisor should not be null');
        }
    }
}